//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ass3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class cars
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "CarMode is Required")]
        public string CarMode { get; set; }
         [Required(ErrorMessage = "Please select company")]
        public Nullable<int> Company { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual companies companies { get; set; }
    }
}
