//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ass3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class companies
    {
        public companies()
        {
            this.cars = new HashSet<cars>();
        }
    
        public int Id { get; set; }
         [Required(ErrorMessage = "Company name is Required")]
        public string Company { get; set; }
         [Required(ErrorMessage = "Country is Required")]
        public string Country { get; set; }
    
        public virtual ICollection<cars> cars { get; set; }
    }
}
